AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an EC2 instance with specified parameters.

Parameters:
  InstanceName:
    Type: String
    Description: Name tag for the EC2 instance.
  AmiId:
    Type: AWS::EC2::Image::Id
    Description: The AMI ID for the EC2 instance.
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t3.micro
      - t3.small
      - t3.medium
    Description: EC2 instance type.
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The name of an existing EC2 KeyPair to enable SSH access.
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC where the instance will be launched.
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: The Subnet where the instance will be launched.

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiId
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetId
      Tags:
        - Key: Name
          Value: !Ref InstanceName

Outputs:
  InstanceId:
    Description: The Instance ID of the created EC2 instance.
    Value: !Ref EC2Instance
  PublicIp:
    Description: The public IP of the created EC2 instance (if applicable).
    Value: !GetAtt EC2Instance.PublicIp
